/******************************************************************************/
/****         Generated by IBExpert 2006.12.13 10/06/2024 14:43:42         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'localhost:D:\ProjetoFortes\BaseDados\Abastecimentos3.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ABASTECIMENTO;
SET GENERATOR GEN_ABASTECIMENTO TO 11;

CREATE GENERATOR GEN_ABASTECIMENTO_BOMBA_TANQUE;
SET GENERATOR GEN_ABASTECIMENTO_BOMBA_TANQUE TO 11;

CREATE GENERATOR GEN_BOMBA;
SET GENERATOR GEN_BOMBA TO 3;

CREATE GENERATOR GEN_BOMBATANQUE;
SET GENERATOR GEN_BOMBATANQUE TO 3;

CREATE GENERATOR GEN_COMBUSTIVEL;
SET GENERATOR GEN_COMBUSTIVEL TO 4;

CREATE GENERATOR GEN_TANQUE;
SET GENERATOR GEN_TANQUE TO 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ABASTECIMENTO (
    ID    INTEGER NOT NULL,
    DATA  TIMESTAMP
);


CREATE TABLE ABASTECIMENTO_BOMBA_TANQUE (
    ID               INTEGER NOT NULL,
    IDABASTECIMENTO  INTEGER,
    IDBOMBATANQUE    INTEGER,
    QUANTIDADE       DOUBLE PRECISION,
    VALOR_UNITARIO   DOUBLE PRECISION,
    TOTAL            DOUBLE PRECISION
);


CREATE TABLE BOMBA (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(60)
);


CREATE TABLE BOMBA_TANQUE (
    ID        INTEGER NOT NULL,
    IDTANQUE  INTEGER,
    IDBOMBA   INTEGER
);


CREATE TABLE COMBUSTIVEL (
    ID              INTEGER NOT NULL,
    DESCRICAO       VARCHAR(60),
    IMPOSTO         DOUBLE PRECISION,
    VALOR_UNITARIO  DOUBLE PRECISION
);


CREATE TABLE TANQUE (
    ID             INTEGER NOT NULL,
    DESCRICAO      VARCHAR(60),
    IDCOMBUSTIVEL  INTEGER
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID);
ALTER TABLE ABASTECIMENTO_BOMBA_TANQUE ADD CONSTRAINT PK_ABASTECIMENTO_BOMBA_TANQUE PRIMARY KEY (ID);
ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA PRIMARY KEY (ID);
ALTER TABLE BOMBA_TANQUE ADD CONSTRAINT PK_BOMBA_TANQUE PRIMARY KEY (ID);
ALTER TABLE COMBUSTIVEL ADD CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY (ID);
ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO_BOMBA_TANQUE ADD CONSTRAINT FK_ABASTECIMENTO_BOMBA_TANQUE_1 FOREIGN KEY (IDBOMBATANQUE) REFERENCES BOMBA_TANQUE (ID) ON DELETE CASCADE
  USING INDEX FK_ABASTECIMENTO_BOMBA_TANQUE_3;
ALTER TABLE ABASTECIMENTO_BOMBA_TANQUE ADD CONSTRAINT FK_ABASTECIMENTO_BOMBA_TANQUE_2 FOREIGN KEY (IDABASTECIMENTO) REFERENCES ABASTECIMENTO (ID) ON DELETE CASCADE;
ALTER TABLE BOMBA_TANQUE ADD CONSTRAINT FK_BOMBA_TANQUE_2 FOREIGN KEY (IDTANQUE) REFERENCES TANQUE (ID) ON DELETE CASCADE;
ALTER TABLE BOMBA_TANQUE ADD CONSTRAINT FK_BOMBA_TANQUE_3 FOREIGN KEY (IDBOMBA) REFERENCES BOMBA (ID) ON DELETE CASCADE;
ALTER TABLE TANQUE ADD CONSTRAINT FK_TANQUE_COMBUSTIVEL FOREIGN KEY (IDCOMBUSTIVEL) REFERENCES COMBUSTIVEL (ID) ON DELETE CASCADE
  USING INDEX FK_TANQUE_1;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM;


/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ABASTECIMENTO_BI0 */
CREATE TRIGGER ABASTECIMENTO_BI0 FOR ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_abastecimento, 1);
end;


/* Trigger: ABASTECIMENTO_BOMBA_TANQUE_BI0 */
CREATE TRIGGER ABASTECIMENTO_BOMBA_TANQUE_BI0 FOR ABASTECIMENTO_BOMBA_TANQUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_abastecimento_bomba_tanque, 1);
end;


/* Trigger: BOMBA_BI0 */
CREATE TRIGGER BOMBA_BI0 FOR BOMBA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_bomba, 1);
end;


/* Trigger: BOMBA_TANQUE_BI0 */
CREATE TRIGGER BOMBA_TANQUE_BI0 FOR BOMBA_TANQUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_bombatanque, 1);
end;


/* Trigger: COMBUSTIVEL_BI0 */
CREATE TRIGGER COMBUSTIVEL_BI0 FOR COMBUSTIVEL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_combustivel, 1);
end;


/* Trigger: TANQUE_BI0 */
CREATE TRIGGER TANQUE_BI0 FOR TANQUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_tanque, 1);
end;


SET TERM ;



/******************************************************************************/
/****                                Roles                                 ****/
/******************************************************************************/

CREATE ROLE RDB$ADMIN;
